// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxdyirsmwywqfmanirsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4ZHlpcnNtd3l3cWZtYW5pcnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTYyMjAsImV4cCI6MjA3MzU5MjIyMH0.KxsgchOkIgQfeQrfoUucbCirVnMgjyt7lRcuXNumaOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});